project:
  type: book

book:
  title: "Design Pattern"
  author: "Kittipos Sirivongrungson"
  repo-url: https://github.com/Lightbridge-KS/design-patterns
  site-url: https://design-patterns-lightbridge.netlify.app
  date: today
  chapters:
    - index.qmd
    - part: OOP
      chapters:
       - "contents/oop/oop-cheatsheet.qmd"
       - "contents/oop/oop-basic.qmd" 
       - "contents/oop/oop-classes.qmd"
       - "contents/oop/oop-relation.qmd"
       - "contents/oop/oop-relation-ex1.qmd"
    - part: Pattern
      chapters: 
       - "contents/pattern/composition-over-inherits.qmd"
       - "contents/pattern/dependency-injection.qmd"
       - "contents/DI/DI_late-binding.qmd"
       - "contents/DI/DI_decorator-pattern.qmd"
       - "contents/DI/DI_decorator-cs-vs-py.qmd"
       - "contents/pattern/template-method.qmd"
    - part: Transport
      chapters: 
        - "contents/pattern/dto-explained.qmd"
    - part: API 
      chapters: 
        - "contents/api/restapi-design-bookstore.qmd"
        - "contents/api/restapi-ml-medical-image.qmd"
    - part: Database
      chapters: 
        - "contents/pattern/db-isomorphic-mapping.qmd"
    - part: Python Design Pattern
      chapters: 
        - "contents/python-pattern/py-SOLID.qmd"
        - "contents/python-pattern/py-abc-vs-protocol.qmd"
        - "contents/python-pattern/py-abc-vs-protocol-details.qmd"
        - "contents/python-pattern/py-ddd.qmd"
    - part: App Architecture
      chapters: 
        - "contents/app-architect/app-arch-layered.qmd"
        - "contents/app-architect/app-arch-layered-vs-tier.qmd"
        - "contents/app-architect/app-arch-scale-up-vs-out.qmd"
        - "contents/app-architect/app-arch-clean-architecture.qmd"
        - "contents/app-architect/app-arch-core.qmd"
        - "contents/app-architect/app-arch-clean-architect-dotnet.qmd"
    - part: Cloud
      chapters: 
        - text: "Cloud Service"
          href: "contents/cloud/cloud-service-model.qmd"
        - text: "Middleware"
          href: "contents/cloud/middleware.qmd"
        - text: "API Gateway vs MiddleWare"
          href: "contents/cloud/api-gateway-vs-middleware.qmd"
    - part: Repository Architecture
      chapters: 
        - "contents/repo-architect/microservice-acme-ai.qmd"
        - "contents/repo-architect/monorepos_multi-client.qmd"
        - "contents/repo-architect/monorepos_reactvite_fastapi.qmd"
        - "contents/repo-architect/monorepos_react-nextjs-fastapi.qmd"
        - "contents/repo-architect/monorepos_reactvite_dotnet.qmd"
        - "contents/repo-architect/monorepos_react-nextjs_dotnet.qmd"
    - part: LLM landscape
      chapters: 
        - "contents/llm/llm-backend-landscape-2025.qmd"
    - part: Bussiness
      chapters: 
        - "contents/bussiness/as_a_service.qmd"
        
bibliography: references.bib

format:
  html:
    lightbox: true
    theme:
      light:
        - simplex
      dark:
        - darkly
      
